server:
  port: 8088


spring:
  datasource:
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/supermarket?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    devtools:
      restart:
        enabled: true
  mvc:
    static-path-pattern: /static/**

  servlet:
    multipart:
      enabled: true
      max-file-size: 10
      max-request-size: 100

mybatis:
  mapper-locations: classpath:mapper/*.xml

#分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


